language: ruby
sudo: false
bundler_args: --without development extra
before_script:
  - echo $TRAVIS_BUILD_DIR
  - ls -l $TRAVIS_BUILD_DIR/ext
  #- chmod +x $TRAVIS_BUILD_DIR/ext/travisci/rubosecscan.sh
  #- $TRAVIS_BUILD_DIR/ext/travisci/rubosecscan.sh
script:
  - echo $TRAVIS_BUILD_DIR
  - ls -l $TRAVIS_BUILD_DIR/ext/travisci
  # - "bundle exec rake $CHECK"
  # if [ "$ext" == "clj" ]; then
notifications:
  email: false
rvm:
  - 2.4.0
  - 2.3.1
  - 2.2.4
  - 2.1.9
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"
  - "CHECK=commits"

matrix:
  exclude:
    - rvm: 2.4.0
      env: "CHECK=rubocop"
    - rvm: 2.3.1
      env: "CHECK=rubocop"
    - rvm: 2.2.4
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
    - rvm: 1.9.3
      env: "CHECK=rubocop"
    - rvm: 2.4.0
      env: "CHECK=commits"
    - rvm: 2.3.1
      env: "CHECK=commits"
    - rvm: 2.2.4
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
